### ISSUE TITLE
Minimum Remove to Make Valid Parentheses

### ISSUE THREAD

**Issue by jungsh16** [Uplift-0508/JoyAlgorithm#1]
https://leetcode.com/explore/challenge/card/february-leetcoding-challenge-2021/586/week-3-february-15th-february-21st/3645/

**Comment by jungsh16** [comment]
```java
class Solution {

    private static final char MARKER_CHAR = '#';

	public String minRemoveToMakeValid(String input) {
		StringBuilder result = new StringBuilder(input);

		Queue<Integer> openIdxQueue = new LinkedList<>();
		Queue<Integer> closeIdxQueue = new LinkedList<>();

		for (int idx = 0; idx < input.length(); idx++) {
			char curChar = input.charAt(idx);
			if (curChar == '(') {
				openIdxQueue.add(idx);
			} else if (curChar == ')') {
				closeIdxQueue.add(idx);
			}
		}

		while (!openIdxQueue.isEmpty()) {
			Integer openIdx = openIdxQueue.peek();
			Integer closeIdx = closeIdxQueue.peek();
			if (closeIdx == null) {
				break;
			}

			if (openIdx < closeIdx) {
				openIdxQueue.poll();
				closeIdxQueue.poll();
			} else {
				closeIdxQueue.poll();
				result.setCharAt(closeIdx, MARKER_CHAR);
			}
		}

		openIdxQueue.forEach(openIdx -> result.setCharAt(openIdx, MARKER_CHAR));
		closeIdxQueue.forEach(closeIdx -> result.setCharAt(closeIdx, MARKER_CHAR));

		return result.toString().replaceAll("#", "");
	}
}
```

**Comment by Uplift-0508** [comment]
public String minRemoveToMakeValid(String input) {
        Stack stack = new Stack();
        List<Integer> listToRemove = new ArrayList<>();
        for (int index = 0; index < input.length(); index++) {
            if (input.charAt(index) == '(') {
                stack.add(index);
            } else if (input.charAt(index) == ')') {
                if (stack.size() > 0) {
                    stack.pop();
                } else {
                    listToRemove.add(index);
                }
            }
        }
        if (stack.size() > 0) {
            listToRemove.addAll(stack);
        }
        listToRemove.sort(Comparator.naturalOrder());

        char[] targetList = input.toCharArray();
        char[] resultList = new char[input.length() - listToRemove.size()];
        int indexToRemove = 0;
        int resultIndex = 0;

        for (int targetIndex = 0; targetIndex < targetList.length; targetIndex++) {
            if (indexToRemove < listToRemove.size() && targetIndex == listToRemove.get(indexToRemove)) {
                indexToRemove++;
            } else {
                resultList[resultIndex++] = targetList[targetIndex];
            }
        }
        return String.valueOf(resultList);
    }
